version: '3'
services:
  db:
    image: postgres:latest
    networks:
      - ${EXTERNAL_NETWORK_NAME}
    volumes:
      - ./dockerfiles/init-sql:/docker-entrypoint-initdb.d
      - ${PG_DATA_FOLDER}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${DB_DATABASE}

  main-index:
    image: darren9276/opi-main-index:2024.01.28
    networks:
      - ${EXTERNAL_NETWORK_NAME}
    volumes:
      - ${LOCAL_BITCOIN_CHAIN_FOLDER}:${BITCOIN_CHAIN_FOLDER}
      - ${LOCAL_ORD_INDEX_FILE}:/app/ord/target/release/index.redb
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SSL=${DB_SSL}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_MAX_CONNECTIONS=${DB_MAX_CONNECTIONS}
      - BITCOIN_CHAIN_FOLDER=${BITCOIN_CHAIN_FOLDER}
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWD=${BITCOIN_RPC_PASSWD}
      - BITCOIN_RPC_URL=${BITCOIN_RPC_URL}
      - ORD_BINARY=${ORD_BINARY}
      - ORD_FOLDER=${ORD_FOLDER}
      - ORD_DATADIR=${ORD_DATADIR}
      - NETWORK_TYPE=${NETWORK_TYPE}

  brc20-index:
    image: darren9276/opi-brc20-index:2024.01.26
    networks:
      - ${EXTERNAL_NETWORK_NAME}
    volumes:
      - ${LOCAL_ORD_INDEX_FILE}:/app/ord/target/release/index.redb
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWD=${DB_PASSWD}
      - DB_METAPROTOCOL_USER=${DB_METAPROTOCOL_USER}
      - DB_METAPROTOCOL_HOST=${DB_METAPROTOCOL_HOST}
      - DB_METAPROTOCOL_PORT=${DB_METAPROTOCOL_PORT}
      - DB_METAPROTOCOL_DATABASE=${DB_METAPROTOCOL_DATABASE}
      - DB_METAPROTOCOL_PASSWD=${DB_METAPROTOCOL_PASSWD}
      - NETWORK_TYPE=${NETWORK_TYPE}
      - REPORT_TO_INDEXER=${REPORT_TO_INDEXER}
      - REPORT_URL=${REPORT_URL}
      - REPORT_RETRIES=${REPORT_RETRIES}
      - REPORT_NAME=${REPORT_NAME}
      - CREATE_EXTRA_TABLES=${CREATE_EXTRA_TABLES}

networks:
  opi-2:
    external: true