FROM rust as rust-builder

WORKDIR /build
ADD . .
# RUN ls -al
RUN cd ord && cargo fetch
RUN cd ord && cargo build --release

RUN mkdir -p /app/ord/target

VOLUME /app/ord/target

CMD ["cp", "-r", "/build/ord/target", "/app/ord/"]